version: '3.8'

services:
  cookie-confusion-toolkit:
    build: .
    environment:
      - DISPLAY=:99
    volumes:
      - ./results:/app/results
      - ./auth.json:/app/auth.json
    command: ["full", "https://example.com", "--verbose"]
    
  # Alternative service for interactive use
  cct-interactive:
    build: .
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:99
    volumes:
      - ./results:/app/results
      - ./auth.json:/app/auth.json
      - ./examples:/app/examples
    entrypoint: ["/usr/local/bin/start-xvfb.sh", "bash"]
