name: Auto-format on Push

on:
  push:
    branches: [ main, develop ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install formatting tools
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    
    - name: Format with Black
      run: black .
    
    - name: Sort imports with isort
      run: isort .
    
    - name: Check for changes
      id: changes
      run: |
        if git diff --exit-code; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-format with Black and isort [skip ci]"
        git push
